### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by AndrewAubury** [schmertenk/HighscoreManager#1]
It would seem your high score server is offline.

Are you able to open source the high score server side?

**Comment by schmertenk** [comment]
Hey,

Sorry. I made some breaking changes to the server side recently, but didn't maintain this repo. (I Didn't know someone is actually using this 😄)
This script is pretty outdated, I'm gonna fix it in the next couple of days.

**Comment by AndrewAubury** [comment]
Heya I'm not using it yet but It looks like it will fit perfectly with what I am trying to do

**Comment by schmertenk** [comment]
Which Godot Version die you use?

**Comment by schmertenk** [comment]
hey there. so in short, this script is now part of a bigger project of mine. the leaderboard manager.
This is a small tool to create and manage highscoreboards for my API. There you can generate a functional GD file if you use Godot. If not there is a detailed description for my API as well.
You can find it here:
https://kitchen-games.itch.io/leaderboardmanager


If there are more questions, I'd be glad to help!
